# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    orchestratorConnection: 'UiPathOrchestratorConnection'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
    traceLevel: 'Information'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'NuGetTestDeveloper1.pfx'



- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'UiPathOrchestratorConnection'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'AzureDevOpsFolder'
    traceLevel: 'Information'
