# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    orchestratorConnection: 'UiPathOrchestratorConnection'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
    traceLevel: 'Information'

- task: DownloadSecureFile@1
  name: caCertificate
  displayName: 'Download CA certificate'
  inputs:
    secureFile: 'NuGetTestDeveloper1.pfx'

- script: |
    echo Installing $(caCertificate.secureFilePath)
    sudo chown root:root $(caCertificate.secureFilePath)
    sudo chmod a+r $(caCertificate.secureFilePath)
    sudo ln -s -t /etc/ssl/certs/ $(caCertificate.secureFilePath)

- task: NuGetCommand@2
  displayName: 'Signing certificate'
  inputs:
    command: 'custom'
    arguments: 'nuget sign $(Build.ArtifactStagingDirectory)\Output -CertificatePath .\..\NuGetTestDeveloper1.pfx -CertificatePassword 1234'

- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'UiPathOrchestratorConnection'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'AzureDevOpsFolder'
    traceLevel: 'Information'
